apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 5004
    targetPort: 5004
    name: http
    protocol: TCP
  selector:
    app: user-service